version: '3'
services:
    mynode:
        container_name: docker-node-app
        restart: always
        build: .
        ports:
            - '80:3000'
        links:
            - mongo
    mongo:
        container_name: docker-node-mongo
        image: mongo
        ports:
            - '27017:27017'
